# Site settings
title: Michael L. Rivera
email: mrivera@colorado.edu #mlrivera@andrew.cmu.edu #mike@mikeriv.com
description: > # this means to ignore newlines until "baseurl:"
  Technical HCI Researcher
baseurl:   # the subpath of your site, e.g. /blog/
url:  https://www.mikeriv.com # the base hostname & protocol for your site
twitter_username: mriveralee
github_username:  mriveralee
linkedin_username: mikeriv
google_scholar_url: https://scholar.google.com/citations?hl=en&user=n7yV9DYAAAAJ
url_for_cv: https://drive.google.com/file/d/1fq2VD2Uh7cKkp5sG0HCtsMvs0GAojTCE/view?usp=sharing #https://drive.google.com/file/d/1-hlDACHBJj3-M6Vw39yB0xhxuyww3jPD/view?usp=sharing
job_materials:
    url_for_research_statement: https://drive.google.com/file/d/1rzayRl-XBE2ZT7uLFWux2me4c577lg-D/view?usp=sharing
    url_for_teaching_statement: https://drive.google.com/file/d/1dmKfy2Y4TOdxlxhtFFguwcQmSwV43sLB/view?usp=sharing
    url_for_diversity_statement: https://drive.google.com/file/d/1UlzIC7yOrZhq0q2oTIiv_9wYu0pfU-bk/view?usp=sharing
path_to_cv: /assets/downloads/RIVERA_MICHAEL_CV.pdf
path_to_research: '/#research-section' #/research/
path_to_music: '/music/'
path_to_updates: '/updates/'
linkSeparator: "-"
keywords: technical hci research, human-computer interaction, michael l. rivera, mriveralee, mike rivera, hcii, phd, fabrication, 3d printing, interactivity, 3D printing, textiles, fabrication

unstableDesignUrl: https://unstable.design/
lauraDevendorfUrl: http://artfordorks.com/
cuAtlasUrl: https://www.colorado.edu/atlas/
cuBoulderWebsiteUrl: https://www.colorado.edu/
ciFellows2021Url: https://cifellows2021.org/
scottHudsonUrl: http://www.cs.cmu.edu/~hudson/
devlabWebsiteUrl: https://cmu-devlab.github.io/
cmuWebsiteUrl: https://cmu.edu
cmuCSDeptWebsiteUrl: https://cs.cmu.edu
cmuHCIIDeptWebsiteUrl: https://hcii.cmu.edu
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      includedInNav: false
      layout: page
      published: true
      isPreview: false
assetsDir: /assets

# Show Future dated posts by default
future: true

# Build settings
markdown: kramdown
highlighter: rouge
timezone: America/New_York
sass:
    sass_dir: _sass
    style: compressed
feed:
  path: feed.xml

# Pagination
paginate: 5
paginate_path: "/blog/page:num/"

google_analytics: UA-26246031-4

collections:
  portfolio:
    output: false
    permalink: /portfolio/:path/
  research:
    output: true
    future: true
    permalink: /research/:path/
  music:
    output: true
    permalink: /music/:path/
  notes:
    output: true
    permalink: /notes/:path/
# Jekyll-scholar settings
scholar:
    style: acm-sigchi-proceedings
    locale: en
    source: ./_bibliography
    bibliography: references.bib

plugins:
  - jekyll-paginate
  - feedjira
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll/scholar

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - examples
  - old_site
  - old_pages
  - photo-editing
  - Rakefile
  - bios.txt
