# Site settings
title: Michael L. Rivera
email: mlrivera@andrew.cmu.edu #mike@mikeriv.com
description: > # this means to ignore newlines until "baseurl:"
  Technical HCI Researcher
baseurl:   # the subpath of your site, e.g. /blog/
url:  https://www.mikeriv.com # the base hostname & protocol for your site
twitter_username: mriveralee
github_username:  mriveralee
linkedin_username: mikeriv
path_to_cv: /assets/downloads/RIVERA_MICHAEL_CV.pdf
path_to_research: '/#research-section' #/research/
path_to_music: '/music/'
path_to_updates: '/updates/'
linkSeparator: "-"
keywords: technical hci research, human-computer interaction, michael l. rivera, mriveralee, mike rivera, hcii, phd, fabrication, 3d printing, interactivity, 3D printing, textiles, fabrication
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      includedInNav: false
      layout: page
      published: true
assetsDir: /assets

# Show Future dated posts by default
future: true

# Build settings
markdown: kramdown
highlighter: rouge
timezone: America/New_York
sass:
    sass_dir: _sass
    style: compressed
feed:
  path: feed.xml

# Pagination
paginate: 5
paginate_path: "/blog/page:num/"

google_analytics: UA-26246031-4

collections:
  portfolio:
    output: true
    permalink: /portfolio/:path/
  research:
    output: true
    future: true
    permalink: /research/:path/
  music:
    output: true
    permalink: /music/:path/

plugins:
  - jekyll-paginate
  - feedjira
  - jekyll-sitemap
  - jekyll-redirect-from

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
  - examples
  - old_site
  - old_pages
