# Site settings
title: Michael L. Rivera
index_title: latest
email: mike@mikeriv.com
description: > # this means to ignore newlines until "baseurl:"
  3rd Year PhD Student in Human-Computer Interaction
baseurl:   # the subpath of your site, e.g. /blog/
url:  http://wwww.mikeriv.com # the base hostname & protocol for your site
twitter_username: mriveralee
github_username:  mriveralee
linkedin_username: mikeriv
path_to_cv: /downloads/RIVERA_MICHAEL_CV.pdf
path_to_research: /research/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      includedInNav: false
      layout: page
      isLiveProjectPage: false

assetsDir: /assets

# Build settings
markdown: kramdown
highlighter: rouge
timezone: America/New_York
sass:
    sass_dir: _sass
    style: compressed
feed:
  path: feed.xml

# Pagination
paginate: 5
paginate_path: "/blog/page:num/"

google_analytics: UA-26246031-4

collections:
  portfolio:
    output: true
    permalink: /portfolio/:path/
  research:
    output: true
    permalink: /research/:path/
  poetry:
    output: true
    permalink: /poetry/:path/
  music:
    output: true
    permalink: /music/:path/

plugins:
  - jekyll-paginate
  - feedjira
  - jekyll-sitemap

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
